<?php
/**
 * @category Internship
 * @package Internship\BinancePay
 * @author Andrii Tomkiv <tomkivandrii18@gmail.com>
 * @copyright 2024 Tomkiv
 */
?>
<?php
/**
 * @var \Internship\BinancePay\Block\CryptoPrice $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Internship_BinancePay/js/binance-price": {
                "symbol": "<?= $escaper->escapeHtml($block->getSymbol()) ?>",
                "storeCurrency": "<?= $escaper->escapeHtml($block->getStoreCurrency()) ?>"
            }
        }
    }
</script>
